var templates = {};

templates.movie = [

    '<div class="cover-box">',
      '<img src="<%= cover %>"/>',
    '</div>',

    '<div class="detail-box">',
      '<h2><%= title %> <span><%= release %></span></h2>',
      '<p><%= plot %></p>',
      '<h2>Rating: <%= rating %>/10</h2>',
      '<button class="edit-btn btn btn-warning">edit</button>',
      '<button class="delete-btn btn btn-danger">delete</button>',
    '</div>',

    '<div class="edit-detail-box hidden">',
      '<form class="popout-form" action="index.html" method="post">',
        '<div class="form-group">',
          '<label for="edit-title">Title</label>',
          '<input type="text" class="form-control edit-title" name="title" value="<%= title %>">',
        '</div>',
        '<div class="form-group">',
          '<label for="edit-release">Release</label>',
          '<input type="text" class="form-control edit-release" name="release" value="<%= release %>">',
        '</div>',
        '<div class="form-group">',
          '<label for="edit-plot">Plot</label>',
          '<textarea class="form-control edit-plot" placeholder="<%= plot %>" name="plot"></textarea>',
        '</div>',
        '<div class="form-group">',
          '<label for="edit-cover">Cover URL</label>',
          '<input type="text" class="form-control edit-cover" name="cover" value="<%= cover %>">',
        '</div>',
        '<div class="form-group">',
          '<label for="edit-rating">Rating:</label>',
          '<select class="form-control edit-rating" name="" value="<%= rating %>">',
            '<option value="1">1</option>',
            '<option value="2">2</option>',
            '<option value="3">3</option>',
            '<option value="4">4</option>',
            '<option value="5">5</option>',
          '</select>',
        '</div>',
        '<button class="submit-btn btn btn-success">Submit</button>',
        '<button class="cancel-btn btn btn-danger">Cancel</button>',
      '</form>',
    '</div>',

].join('');

templates.addMovie = [
  '<button type="button" class="btn btn-success" id="add-btn" data-toggle="modal" data-target="#MyModal">Add New Movie</button>',

  '<div class="modal fade" id="MyModal"tabindex="-1" role="dialog">',
    '<div class="modal-dialog">',
      '<div class="modal-content">',
        '<div class="modal-header">',
          '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
          '<h4 class="modal-title">New Movie</h4>',
        '</div>',
        '<div class="modal-body">',
          '<form id="new-movie">',
            '<div class="form-group">',
              '<label for="new-title">Title</label>',
              '<input type="text" class="form-control new-title" placeholder="">',
            '</div>',
            '<div class="form-group">',
              '<label for="new-release">Release Date</label>',
              '<input type="text" class="form-control new-release" placeholder="">',
            '</div>',
            '<div class="form-group">',
              '<label for="new-plot">Plot</label>',
              '<textarea name="plot" class="form-control new-plot"></textarea>',
            '</div>',
            '<div class="form-group">',
              '<label for="new-cover">Cover URL</label>',
              '<input type="text" class="form-control new-cover" name="cover">',
            '</div>',
            '<div class="form-group">',
              '<label for="edit-rating">Rating:</label>',
              '<select class="form-control edit-rating" name="">',
                '<option value="1">1</option>',
                '<option value="2">2</option>',
                '<option value="3">3</option>',
                '<option value="4">4</option>',
                '<option value="5">5</option>',
              '</select>',
            '</div>',
          '</form>',
        '</div>',
        '<div class="modal-footer">',
          '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
          '<button type="button" class="add-btn btn btn-primary" data-dismiss="modal">Submit</button>',
        '</div>',
      '</div><!-- /.modal-content -->',
    '</div><!-- /.modal-dialog -->',
  '</div><!-- /.modal -->',

].join('');
var movies = [
  {
    title: "COCCOON",
    release: 2016,
    cover: "http://ecx.images-amazon.com/images/I/517VJT3V6FL.jpg",
    plot: "Harry Potter and the Goblet of Fire is a 2005 fantasy film directed by Mike Newell and distributed by Warner Bros. Pictures.[2] It is based on the novel of the same name by J. K. Rowling. The film, which is the fourth instalment in the Harry Potter film series, was written by Steve Kloves and produced by David Heyman. The story follows Harry Potter's fourth year at Hogwarts as he is chosen by the Goblet of Fire to compete in the Triwizard Tournament.",
    rating: 8,
  },
  {
    title: "Brown-Eyed Girl",
    release: 2016,
    cover: "http://ecx.images-amazon.com/images/I/517VJT3V6FL.jpg",
    plot: "Harry Potter and the Goblet of Fire is a 2005 fantasy film directed by Mike Newell and distributed by Warner Bros. Pictures.[2] It is based on the novel of the same name by J. K. Rowling. The film, which is the fourth instalment in the Harry Potter film series, was written by Steve Kloves and produced by David Heyman. The story follows Harry Potter's fourth year at Hogwarts as he is chosen by the Goblet of Fire to compete in the Triwizard Tournament.",
    rating: 8,
  },
  {
    title: "Weekend at Bernie's",
    release: 2016,
    cover: "http://ecx.images-amazon.com/images/I/517VJT3V6FL.jpg",
    plot: "Harry Potter and the Goblet of Fire is a 2005 fantasy film directed by Mike Newell and distributed by Warner Bros. Pictures.[2] It is based on the novel of the same name by J. K. Rowling. The film, which is the fourth instalment in the Harry Potter film series, was written by Steve Kloves and produced by David Heyman. The story follows Harry Potter's fourth year at Hogwarts as he is chosen by the Goblet of Fire to compete in the Triwizard Tournament.",
    rating: 8,
  },
  {
    title: "Harry Potter and the Goblet of Fire",
    release: 2016,
    cover: "http://ecx.images-amazon.com/images/I/517VJT3V6FL.jpg",
    plot: "Harry Potter and the Goblet of Fire is a 2005 fantasy film directed by Mike Newell and distributed by Warner Bros. Pictures.[2] It is based on the novel of the same name by J. K. Rowling. The film, which is the fourth instalment in the Harry Potter film series, was written by Steve Kloves and produced by David Heyman. The story follows Harry Potter's fourth year at Hogwarts as he is chosen by the Goblet of Fire to compete in the Triwizard Tournament.",
    rating: 8,
  },
];
